# Generated by Django 2.2.1 on 2019-06-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='texto',
            field=models.TextField(max_length=200, verbose_name='Texto'),
        ),
    ]
